In [10]:
from mlflow.recipes import Recipe
import pandas as pd


In [14]:
df = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6], 'target': ['a', 'b', 'c']})
df.to_csv('../data/df.csv')

In [15]:
r = Recipe(profile="local")

2024/04/03 11:52:33 INFO mlflow.recipes.recipe: Creating MLflow Recipe 'my_project' with profile: 'local'


In [16]:
r.clean()

In [17]:
r.inspect()

In [18]:
r.run("ingest")

2024/04/03 11:52:37 INFO mlflow.recipes.step: Running step ingest...
****************************************************************************************************
csv
****************************************************************************************************


In [6]:
import subprocess
subprocess.run(["make", "--help"], check=True)

CompletedProcess(args=['make', '--help'], returncode=0)

In [19]:
ingested_data_path = 'C:/Users/honek/.mlflow/recipes/1991bd051264205cf200c35d8ec0ad004b0d606a1a493437e999d7871c3781fe/steps/ingest/outputs/dataset.parquet'
df_from_parquet = pd.read_parquet(ingested_data_path)

In [20]:
df_from_parquet

Unnamed: 0  col1  col2 target
0           0     1     4      a
1           1     2     5      b
2           2     3     6      c

In [21]:
import tensorflow as tf

In [23]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [26]:
import numpy as np

# Example 3D array
array_3d = np.random.rand(2, 3, 4)  # Example 3D array of shape (2, 3, 4)

# Reshape the array to flatten the last two dimensions
array_2d = array_3d.reshape(-1, array_3d.shape[1] * array_3d.shape[2])

# Output the original and flattened arrays
print("Original 3D array:")
print(array_3d)
print("Flattened 2D array:")
print(array_2d)

Original 3D array:
[[[0.69383022 0.07017858 0.85192124 0.06816079]
  [0.77628281 0.83764855 0.8056396  0.05533373]
  [0.95258032 0.97714278 0.57644598 0.96235275]]

 [[0.247656   0.42381255 0.55650927 0.00706274]
  [0.29362226 0.989516   0.66527283 0.66343495]
  [0.25978969 0.4705281  0.95732501 0.19071816]]]
Flattened 2D array:
[[0.69383022 0.07017858 0.85192124 0.06816079 0.77628281 0.83764855
  0.8056396  0.05533373 0.95258032 0.97714278 0.57644598 0.96235275]
 [0.247656   0.42381255 0.55650927 0.00706274 0.29362226 0.989516
  0.66527283 0.66343495 0.25978969 0.4705281  0.95732501 0.19071816]]
